const express = require('express')
const expressServer = express()
const cors = require('cors')
const cookieParser = require('cookie-parser')
const bodyParser = require('body-parser')
const verifyJWT = require('../middleware/verifyJWT')
const credentials = require('../middleware/credentials')
const corsOptions = require('../../config/corsOptions')
const { deviceRoutes } = require('../routes/deviceRoutes')
const { sceneRoutes } = require('../routes/sceneRoutes')
const { groupRoutes } = require('../routes/groupRoutes')
const { userRoutes } = require('../routes/userRoutes')
const { loginRoutes } = require('../routes/loginRoutes')
const { tokenRoutes } = require('../routes/tokenRoutes')
const { smartStripRoutes } = require('../routes/smartStripRoutes')
const { smartIRRoutes } = require('../routes/smartIRRoutes')
const { smartLedRoutes } = require('../routes/smartLedRoutes')
const { smartSirenAlarmRoutes } = require('../routes/smartSirenAlarmRoutes')
const { smartDoorSensorRoutes } = require('../routes/smartDoorSensorRoutes')
const { zbHubRoutes } = require('../routes/zbHubRoutes')

expressServer.use(credentials)
expressServer.use(cors(corsOptions))

expressServer.use(bodyParser.json())
expressServer.use(cookieParser())

expressServer.use('/', loginRoutes)
expressServer.use('/', tokenRoutes)
expressServer.use(verifyJWT)
expressServer.use('/', userRoutes)
expressServer.use('/', deviceRoutes)
expressServer.use('/', sceneRoutes)
expressServer.use('/', groupRoutes)
expressServer.use('/', smartStripRoutes)
expressServer.use('/', zbHubRoutes)
expressServer.use('/', smartIRRoutes)
expressServer.use('/', smartLedRoutes)
expressServer.use('/', smartSirenAlarmRoutes)
expressServer.use('/', smartDoorSensorRoutes)

module.exports = expressServer
